apiVersion: v1
kind: Service
metadata:
  name: kuberneteswk10-service
spec:
  selector:
    app: kuberneteswk10-deployment
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000